# Generated by Django 5.0.3 on 2024-05-02 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_game_ft', models.DateField()),
                ('time_ft', models.TimeField()),
                ('team_ft', models.CharField(max_length=100)),
                ('opponent_ft', models.CharField(max_length=100)),
                ('full_time_goals_scored_ft', models.IntegerField()),
                ('full_time_goals_conceded_ft', models.IntegerField()),
                ('home_ft', models.CharField(max_length=30)),
                ('game_outcome_ft', models.CharField(max_length=20)),
                ('win_ft', models.IntegerField(default=0)),
                ('draw_ft', models.IntegerField(default=0)),
                ('loss_ft', models.IntegerField(default=0)),
                ('points_ft', models.IntegerField()),
                ('half_time_team_goals_scored_ft', models.IntegerField()),
                ('half_time_team_goals_conceded_ft', models.IntegerField()),
                ('half_time_win_ft', models.BooleanField()),
                ('half_time_draw_ft', models.BooleanField()),
                ('half_time_loss_ft', models.BooleanField()),
                ('referee_ft', models.CharField(max_length=100)),
                ('team_shots_recorded_ft', models.IntegerField()),
                ('team_shots_conceded_ft', models.IntegerField()),
                ('team_shots_on_target_recorded_ft', models.IntegerField()),
                ('team_shots_on_target_conceded_ft', models.IntegerField()),
                ('team_fouls_committed_recorded_ft', models.IntegerField()),
                ('team_fouls_committed_conceded_ft', models.IntegerField()),
                ('team_corners_recorded_ft', models.IntegerField()),
                ('team_corners_conceded_ft', models.IntegerField()),
                ('team_yellow_cards_recorded_ft', models.IntegerField()),
                ('team_yellow_cards_conceded_ft', models.IntegerField()),
                ('team_red_cards_recorded_ft', models.IntegerField()),
                ('team_red_cards_conceded_ft', models.IntegerField()),
                ('half_time_outcome_ft', models.CharField(max_length=20)),
                ('season_ft', models.CharField(max_length=20)),
                ('goal_difference_ft', models.IntegerField()),
                ('league', models.CharField(max_length=100)),
                ('more_corners_ft', models.BooleanField()),
                ('more_cards_ft', models.BooleanField()),
            ],
            options={
                'db_table': 'footdata2',
            },
        ),
    ]
